name: linux

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        std: [14, 17, 20]

    steps:
      -   uses: actions/checkout@v3

      -   name: Create Build Environment
          run: |
            sudo apt update
            sudo apt install -y libgtest-dev
            cmake -E make_directory ${{runner.workspace}}/build

      -   name: Configure
          working-directory: ${{runner.workspace}}/build
          run: |
            cmake \
              -D "CMAKE_CXX_STANDARD=${{matrix.std}}" \
              -D "BUILD_DOCS=OFF" \
              ${GITHUB_WORKSPACE}

      -   name: Build
          working-directory: ${{runner.workspace}}/build
          run: cmake --build . --config Release

      -   name: Test
          working-directory: ${{runner.workspace}}/build
          run: ctest -VV
          env:
            CTEST_OUTPUT_ON_FAILURE: True
