name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
      -   uses: actions/checkout@v3

      -   name: Create Build Environment
          run: |
            vcpkg install --triplet=x64-windows gtest
            cmake -E make_directory ${{runner.workspace}}/build

      -   name: Configure
          shell: bash
          working-directory: ${{runner.workspace}}/build
          run: |
            cmake \
              -G "Visual Studio 16 2019" -A x64 \
              -D "CMAKE_CXX_FLAGS=WIN32_LEAN_AND_MEAN;/wd4273" \
              -D "CMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}\scripts\buildsystems\vcpkg.cmake" \
              -D "VCPKG_TARGET_TRIPLET=x64-windows" \
              -D "BUILD_DOCS=OFF" \
              ${GITHUB_WORKSPACE}

      -   name: Build
          shell: bash
          working-directory: ${{runner.workspace}}/build
          run: cmake --build . --config Release

      -   name: Test
          shell: bash
          working-directory: ${{runner.workspace}}/build
          run: ctest -VV
          env:
            CTEST_OUTPUT_ON_FAILURE: True
