name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        std: [14, 17, 20]

    steps:
      -   uses: actions/checkout@v3

      -   name: Create Build Environment
          run: |
            vcpkg --triplet=x64-windows install gtest
            cmake -E make_directory ${{runner.workspace}}/build

      -   name: Configure
          shell: bash
          working-directory: ${{runner.workspace}}/build
          run: |
            echo 
            cmake \
              -D "CMAKE_CXX_STANDARD=${{matrix.std}}" \
              -D "CMAKE_TOOLCHAIN_FILE=${Env:VCPKG_INSTALLATION_ROOT}\scripts\buildsystems\vcpkg.cmake" \
              -D "VCPKG_TARGET_TRIPLET=x64-windows" \
              -D "BUILD_DOCS=OFF" \
              ${GITHUB_WORKSPACE}

      -   name: Build
          shell: bash
          working-directory: ${{runner.workspace}}/build
          run: cmake --build . --config Release

      -   name: Test
          shell: bash
          working-directory: ${{runner.workspace}}/build
          run: ctest -VV
          env:
            CTEST_OUTPUT_ON_FAILURE: True
